### ISSUE TITLE
How do we install it on Docker ?

### ISSUE THREAD

**Issue by arthurd2** [metsrl/channel-rocketchat#1]
Hey man, first of all: thanks for the module.

Question: There's a right way to install the module in Botpress?

I've try to:
- Git clone in /botpress/modules/channel-rocketchat
- Git clone in /botpress/data/assets/modules/channel-rocketchat
- Put the project's TGZ in /botpress/modules/channel-rocketchat.tgz

But all leads me to one of the following errors:
```
Launcher Error while loading some modules, they will be disabled [VError, Could not find module at path "MODULES_ROOT/channel-rocketchat"],
VError: Could not find module at path "MODULES_ROOT/channel-rocketchat",
STACK TRACE
```
or
```
Launcher Error while loading some modules, they will be disabled [Error, Cannot find module '/botpress/modules/.cache/module__xxxxxx'],
Error: Cannot find module '/botpress/modules/.cache/module__xxxxxx'
```

I'm using Botpress 12.8.5 in Docker.

**Comment by bollinim** [comment]
I've updated the README. Please create a BP development environment as described, in order to build and package the module.
We have spent just few days on development and basically this is a "training on the job" version. Any help and comments are very welcomed
Bye

**Comment by arthurd2** [comment]
Ofc!
If you allow me I can automate it.
I will submit a PR soon.
Grazie!

**Comment by bollinim** [comment]
Go ahead for sure!
